### ISSUE TITLE
Use different vaults defined in .ansible.cfg to encrypt variables

### ISSUE THREAD

**Issue by BojanOro** [timo-reymann/idea-ansible-vault-integration#15]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I maintain a large set of host_vars containing various variables, some encrypted and some not. Each of these host_vars has variables encrypted with a separate vault password since some teams need access to certain hosts and not others. In my `.ansible.cfg` I have 

```
vault_identity_list = my_first_vault@~/ansible/passwords/my_first_vault, my_second_vault@~/ansible/passwords/my_second_vault
```

with each <vault_name>@<password_file> pair being unique for each file. Then, when I go to encrypt a file I simply select which vault ID I want to use to encrypt that file, and get a result like:

```
secret_key: !vault |
            $ANSIBLE_VAULT;1.2;AES256;my_first_vault
            35633365333036663732613030303238663931343336383865323262396330373631393239356530
            3336663965626136353939333062373333626665383066630a616263633538393132323530633364
```

When I run ansible-playbook or go to decrypt that file, Ansible will find that vault ID and password combo and decrypt it without prompting me. At present, this works in the plugin!

My feature request is this: allow users to be prompted when encrypting a variable to select from the defined vaults in your `.ansible.cfg` and encrypt it with that vault ID.

This would also be an alternative nice solution for https://plugins.jetbrains.com/plugin/14353-ansible-vault-integration/tutorials/vault-file-as-script as you could just encrypt your dev/qa/prod variables with different vault IDs.

### References

A VScode version of this: https://gitlab.com/wolfmah/vscode-ansible-vault-inline#experimental-vault-id

https://docs.ansible.com/ansible/latest/user_guide/vault.html#encrypting-individual-variables-with-ansible-vault
https://plugins.jetbrains.com/plugin/14353-ansible-vault-integration/tutorials/vault-file-as-script

**Comment by timo-reymann** [comment]
Hello @BojanOro,

first thank you for using my plugin and the feature request.

That sounds like a really neat feature and a great alternative to the custom script, i will just need some time how to do it. Parsing seems to be very easy, what might take sometime is to figure out which UI to build and how to do it (the docs are very bad here).

**Comment by timo-reymann** [comment]
Will be available with 2.2.0 (via popup for context menu/unvault intention).

If you encounter any problems, feel free to leave a comment and i will reopen this ticket :) 

Short feedback would be highly appreciated, when the new version is available (~ 2-3 days).

**Comment by BojanOro** [comment]
Hi Timo, any idea when 2.2.0 will be out? I'm eager to test this out for you!

**Comment by timo-reymann** [comment]
Sorry, i messed up the ci config and it didn't publish sorry for that. 2.2.0 is currently releasing and will be available at Friday at least.
