### ISSUE TITLE
Increase or make configurable plugin execution timeout

### ISSUE THREAD

**Issue by mazdader** [timo-reymann/idea-ansible-vault-integration#4]
Hello,

In our company we have pretty aggressive antivirus scanning settings which significantly slow down our workstations. As we use the Plugin on Windows, we have a setup when Ansible is installed in Cygwin and we created a wrapper that we use to run Ansible Vault encryption/decryption commands and we specify that wrapper as Ansible Vault binary in the Plugin settings. However due to low workstations performance and with the setup described above it actually takes up to 10-20 seconds to run all components which is way above the limit set in the _src/main/java/com/github/timo_reymann/ansible_vault_integration/execution/vaultaction/AnsibleVaultAction.java_ (3_000). So far to fix the timeout issue we'e been patching the source code and compiling the plugin. But it would be nice if that timeout can be increased by default or become configurable.

**Comment by timo-reymann** [comment]
Hi mazdader,

first thank you for using my plugin and the feature request.
Yeah this seems a valid use case for me. I am going to implement a configurable timeout on the setings page.

**Comment by timo-reymann** [comment]
There we go: https://plugins.jetbrains.com/plugin/14353-ansible-vault-integration/versions/stable/122512

If something should not work feel free to create a issue :)
