### ISSUE TITLE
Plugin does not work with ansible-vault-win - Timeout and no further debug information

### ISSUE THREAD

**Issue by sebastianzillessen** [timo-reymann/idea-ansible-vault-integration#44]
Hello, 

I am trying this Plugin on a Windows Maschine, using IntelliJ 2022.1.3 and the version 2.2.1 of the Plugin. 

Installation of Ansible-Vault with pip:
 
    pip install ansible-vault-win

The `ansible-vault` command works perfectly from the Command Line. I even added the execution Path of the Script to the path.

In a cmd I run: 

    C:\Users\xxxx>where ansible-vault
    C:\Users\xxxx\AppData\Roaming\Python\Python38\Scripts\ansible-vault.exe

I add this path to the plugin config:

     Executable: C:\Users\xxxx\AppData\Roaming\Python\Python38\Scripts\ansible-vault.exe
     Exectution Timeout: 30

When I now click on a file and hit "Vault/Unvault File" I always get a timeout:

    Command timed out:

There is no further details or logs available telling me what is going wrong. 

Can anyone reproduce this?

Thanks!

**Comment by timo-reymann** [comment]
Hi @sebastianzillessen,

The plugin doesn't search the path, but rather uses a configured executable. It sounds like you haven't configured it there.

You can do that in Settings > Tools > Ansible:
![image](https://user-images.githubusercontent.com/21024948/199518867-e1ebeaa3-8e29-4ec7-9096-1dc757648614.png)
(screenshotted on MacOS)

In your case, `/usr/local/bin/ansible-vault` should be set to `C:\Users\xxxx\AppData\Roaming\Python\Python38\Scripts\ansible-vault.exe`

After that, it should work. When no binary is configured, there is no error message, but rather a timeout because the OS cant execute the file.

**Comment by timo-reymann** [comment]
Also implemented precheck in action available after release of 2.3.0 stating the binary configured does not exist.

**Comment by sebastianzillessen** [comment]
Hi @timo-reymann , 

thanks for your fast response. 

I did indeed set the path correctly as mentioned above: 

> I add this path to the plugin config:
> 
>  Executable: C:\Users\xxxx\AppData\Roaming\Python\Python38\Scripts\ansible-vault.exe
>  Exectution Timeout: 30

so I even increased the timeout to 30s to avoid any slow responses. 

Any thought on how to analyse / debug this further? 

Thanks!

**Comment by timo-reymann** [comment]
Hi @sebastianzillessen,
I can't test/troubleshoot Windows. So, unfortunately can't help you with this path.
Also, not sure about ansible-vault-win, if it is using the same interface as the "original" one.

My suspect is that it simply doesn't behave the same way/provides the same features as the ansible-vault.

## Workaround using WSL

What I know to work fine is using WSL2 for the ansible-vault. It's also natively supported by the plugin. To achieve that, install ansible-vault inside a WSL instance and use the WSL path for the executable. 
Should also work graphically with the file picker (haven't worked with though) which displays you the WSL "instances".

The WSL path looks somewhat like this: `\\wsl$\<Distribution>\path\to\file`, it is parsed by the plugin automatically and behaves just like it's executed inside the regular WSL shell.

Cheers,
Timo
